# Astro Program Makefile
# Written by M. Patrick Tkacik
# June 2, 2009

# Variables
OBJ = main.o configurator.o makemodel.o mkabfind.o paramsR.o sortlist.o strcttls.o sttpk.o numrec.o preparams.o
SRC = main.c configurator.c makemodel.c mkabfind.c paramsR.c sortlist.c strcttls.c sttpk.c numrec.c preparams.c
SOB = wrpr.o
SSRC = wrpr.c
FLGS = -lm
DBGFL = -lm -g -Wall
PROG = spnkr
STTY = stty
PTH = /opt/spnkr/
LGPTH= /etc/spnkr/logfiles/


#Default option that runs when "make" is all that is typed
# Only compiles 'SPnKr'
$(PROG): $(OBJ)
	gcc $(OBJ) $(FLGS) -o $(PROG)

# Rule for compiling the STTY wrapper for dealing with MOOG
$(STTY): $(SOB)
	gcc $(SOB) $(FLGS) -o $(STTY)

# Various rulls for dependencies
$(SOB): $(SSRC)	
$(OBJ): $(SRC)
$(SRC): headers.h

# Debug option that compiles SPnKr for use with a debugger
debug: $(OBJ)
	gcc $(SRC) $(DBGFL) -o $(PROG)

# Option for making both SPnKr and the STTY wrapper
all: $(PROG) $(STTY)

# Installs the program and creates the various directories
install: 
	mkdir -p $(PTH);
	cp config.txt /etc/astro.conf
	cp newline.txt /etc/newline.txt
	cp stty $(PTH)stty
	mv $(PROG) /usr/bin/$(PROG)
	cp stelstats.sm /usr/bin/stelstats.sm
	cp moogplots.sm /usr/bin/moogplots.sm

# Uninstalls the program from the installation directories
uninstall:
	rm -r $(PTH)
	rm /etc/astro.conf
	rm $(PTH)stty
	rm /usr/bin/$(PROG)
	
# Tidies up the main source directory and gets rid of
# the backup files generated by gedit
tidy:
	mv *.*~ src/

# Cleans all of the object files and the compiled executable
clean:
	rm $(PROG) $(OBJ) $(STTY) $(SOB)
